### PR TITLE
support for node16, update all packages (mainly amqplib)

### PR DESCRIPTION
**Pull request by szymonskirgajllo**
hello again! ;) i would like to use rabbit-queue with node@16 but amqplib does not support it in 0.7.x version so we need to update amqplib firstly ;) 

how can i add node16 to tests in semaphoreci?

```
➜  rabbit-queue git:(master) ncu
Checking /Users/szymonskirgajllo/workspace/rabbit-queue/package.json
[====================] 20/20 100%

All dependencies match the latest package versions :)
```

### CODE REVIEW

**Comment by szymonskirgajllo** [comment]
@nikostoulas can you help me? please :)

**Comment by manoskouvarakis** [comment]
> @nikostoulas can you help me? please :)

Hello @szymonskirgajllo. Thanks for the contribution. 
We added node 16 tests in semaphore (even if it would be better to be an LTS version firstly).
We will merge this and publish a new version. However, you could manually change your local version to 0.7.0 without any issues. If you use a package-lock for example you could change the version of amqplib there.

**Comment by manoskouvarakis** [comment]
@szymonskirgajllo version 5.3.0 is published

**Comment by szymonskirgajllo** [comment]
@manoskouvarakis thank you so much! <3

**Pull request merged**
